###Get the service document
http://localhost:4004/odata/v4/CatalogService/


###Get the service metadata document
http://localhost:4004/odata/v4/CatalogService/$metadata


###Get All Employees Data
http://localhost:4004/odata/v4/CatalogService/EmployeeSet


###Count All Employees
http://localhost:4004/odata/v4/CatalogService/EmployeeSet/$count


###Get Single Employees Data by its key
http://localhost:4004/odata/v4/CatalogService/EmployeeSet/02BD2137-0890-1EEA-A6C2-BB55C19787FB

###Get All Employees Data - pagination 
http://localhost:4004/odata/v4/CatalogService/EmployeeSet?$top=4&$skip=3


###Get All Employees Data - filter
http://localhost:4004/odata/v4/CatalogService/EmployeeSet?$filter=language eq 'E' and sex eq 'M'

# http://localhost:4004/odata/v4/CatalogService/EmployeeSet?$filter=language eq 'E' and sex eq 'M'


###Get All Employees Data- filter with texts
http://localhost:4004/odata/v4/CatalogService/EmployeeSet?$filter=contains(nameFirst,'Su')


###Get All Employees Data
http://localhost:4004/odata/v4/CatalogService/EmployeeSet?$top=2&$skip=2&$select=ID,nameFirst,email


###Insert Employee data
POST http://localhost:4004/odata/v4/CatalogService/EmployeeSet
Content-Type: application/json

{
      "nameFirst": "Satya",
      "nameMiddle": "",
      "nameLast": "Prakash",
      "nameInitials": null,
      "sex": "M",
      "language": "E",
      "phoneNumber": null,
      "email": "satya@gmail.com",
      "loginName": "SATYA",
      "Currency_code": "USD",
      "salaryAmount": 85962,
      "accountNumber": "8444455465",
      "bankId": "121000358",
      "bankName": "My Bank of San Francisco"
}

###Read the created employee data
http://localhost:4004/odata/v4/CatalogService/EmployeeSet/40025efc-8860-45c4-8877-6e942f75dbf6


###Update employee Salary
PATCH http://localhost:4004/odata/v4/CatalogService/EmployeeSet/40025efc-8860-45c4-8877-6e942f75dbf6
Content-Type: application/json


{
    "salaryAmount": 1000000,
    "Currency_code": "INR",
    "bankName":"SWIZ BANK"
}


###Remove the employee
DELETE http://localhost:4004/odata/v4/CatalogService/EmployeeSet/40025efc-8860-45c4-8877-6e942f75dbf6


###Get all POs
http://localhost:4004/odata/v4/CatalogService/POs


###Get single order by key
http://localhost:4004/odata/v4/CatalogService/POs/74867AD200E41EDBA5D8B0C98DC2E052


###How to leverage the association for items
http://localhost:4004/odata/v4/CatalogService/POs/74867AD200E41EDBA5D8B0C98DC2E052?$expand=Items


###Call the action
POST http://localhost:4004/odata/v4/CatalogService/POs/74867AD200E41EDBA5D8B0C98DC2E052/CatalogService.boost
Content-Type: application/json


{}

###Calling function
http://localhost:4004/odata/v4/CatalogService/largestOrder()


###Get all POs v2 call :
http://localhost:4004/v2/odata/v4/CatalogService/POs
